# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170310_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='myuser_id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Level'),
        ),
    ]
