# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170310_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='level_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Level'),
        ),
    ]
