# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170315_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='level_id',
            new_name='level',
        ),
    ]
