# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170315_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qus', to='accounts.Question'),
        ),
    ]
