# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 13:44
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170317_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='user_answer',
            field=models.IntegerField(verbose_name=accounts.models.Answer),
        ),
    ]
