# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170315_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Answer')),
            ],
        ),
        migrations.DeleteModel(
            name='UserQuestion',
        ),
    ]
