# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170317_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='level_id',
            new_name='level',
        ),
    ]
