# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userinput_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Level'),
        ),
        migrations.AddField(
            model_name='userinput',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Question'),
        ),
    ]
